### ISSUE TITLE
How can I change the help text and example prompts in another language for example in german

### ISSUE THREAD

**Issue by bvs12** [AsyncWeb/bigbluebutton-chatgpt#13]
I can find the "@chatgpt help" texts and example prompts in file app.js. And I have changed them to german. Then i do docker-compose down and docker-compose up -d. When i type in the public chat of bigbluebutton "@chatgpt help" all texts are is still in english. Please give a tip for changing the texts.

**Comment by arun-hel** [comment]
@bvs12  You need to rebuild the docker image  and use that newly built docker image in docker-compose
