### ISSUE TITLE
MongoDB connection issue / timeout

### ISSUE THREAD

**Issue by belorenz** [AsyncWeb/bigbluebutton-chatgpt#7]
Hi everyone, 

I'am getting this problem below and have no clue how to proceed / debug. Could you give a pointer please?
Using BBB 2.5.9.

```shell
Recreating bbb-chatgpt ... done
Attaching to bbb-chatgpt
bbb-chatgpt    | 
bbb-chatgpt    | > bigbluebutton-chatgpt@1.0.0 start
bbb-chatgpt    | > node app.js
bbb-chatgpt    | 
bbb-chatgpt    | Client Connected to Redis
bbb-chatgpt    | Publisher Connected to Redis
bbb-chatgpt    | MongoServerSelectionError: connection <monitor> to 127.0.0.1:4101 closed
bbb-chatgpt    |     at Timeout._onTimeout (/usr/src/app/node_modules/mongodb/lib/sdam/topology.js:284:38)
bbb-chatgpt    |     at listOnTimeout (node:internal/timers:568:17)
bbb-chatgpt    |     at process.processTimers (node:internal/timers:511:7)
```
Best regards!

**Comment by arun-hel** [comment]
@belorenz  You need to update `MONGO_URI` with correct mongodb connection details.

To get mongo db connection details follow the below steps

1.  Install `lsof`. It is used to get the active ports. `sudo apt install lsof`
2. Run `sudo lsof -iTCP -sTCP:LISTEN | grep mongo`. You should get the output similar to  following
```sh
COMMAND    PID    USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
mongod  596858 mongodb   10u  IPv4 42960792      0t0  TCP localhost:27017 (LISTEN)
```
Look at  `localhost:27017 (LISTEN)`, here `27017` is mongo db port.
3. Update `MONGO_URI`. example: `MONGO_URI=mongodb://127.0.0.1:27017/meteor`
4. Restart the containers: `docker-compose down && docker-compose up -d`

**Comment by belorenz** [comment]
Hey @arun-hel thanks for the input. As you pointed out, the port I used was not correct. MongoDB runs on Port `27017`. Thanks for the hint!

Now, instead of a  `connection closed` timeout I get a `ECONNREFUSED` timeout. Is there any kind of authentication which I am missing here? Did the standard BBB installation with `ìnstall-bbb.sh`. Any ideas?

```shell
sudo lsof -iTCP -sTCP:LISTEN | grep mongo
lsof: no pwd entry for UID 472
lsof: no pwd entry for UID 472
mongod    3366377         mongodb   11u  IPv4 63697223      0t0  TCP localhost:27017 (LISTEN)
```

```shell
sudo docker-compose up
Recreating bbb-chatgpt ... done
Attaching to bbb-chatgpt
bbb-chatgpt    | 
bbb-chatgpt    | > bigbluebutton-chatgpt@1.0.0 start
bbb-chatgpt    | > node app.js
bbb-chatgpt    | 
bbb-chatgpt    | Client Connected to Redis
bbb-chatgpt    | Publisher Connected to Redis
bbb-chatgpt    | MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
bbb-chatgpt    |     at Timeout._onTimeout (/usr/src/app/node_modules/mongodb/lib/sdam/topology.js:284:38)
bbb-chatgpt    |     at listOnTimeout (node:internal/timers:568:17)
bbb-chatgpt    |     at process.processTimers (node:internal/timers:511:7)
```

**Comment by belorenz** [comment]
I ran `mongostat` which returned something similar, `connection() error occurred during connection handshake: dial tcp 127.0.0.1:27017: connect: connection refused `

Here the complete output:

```shell
2023-03-01T21:53:45.583+0100	could not connect to server: server selection error: server selection timeout, current topology: { Type: Single, Servers: [{ Addr: localhost:27017, Type: Unknown, Last error: connection() error occurred during connection handshake: dial tcp 127.0.0.1:27017: connect: connection refused }, ] }
```

**Comment by arun-hel** [comment]
@belorenz  try using `mongodb://127.0.1.1:27017/meteor` instead of `mongodb://127.0.0.1:27017/meteor`

**Comment by belorenz** [comment]
```shell
sudo docker-compose up
Creating bbb-chatgpt ... done
Attaching to bbb-chatgpt
bbb-chatgpt    | 
bbb-chatgpt    | > bigbluebutton-chatgpt@1.0.0 start
bbb-chatgpt    | > node app.js
bbb-chatgpt    | 
bbb-chatgpt    | Client Connected to Redis
bbb-chatgpt    | Publisher Connected to Redis
bbb-chatgpt    | Connected successfully to MongoDB
```
Changing the IP from `127.0.0.1:27017` to `127.0.1.1:27017` in the `.env` file did the trick! Thank you @arun-hel !
