### ISSUE TITLE
Does not work. nvm version error

### ISSUE THREAD

**Issue by amishbhavsar** [AsyncWeb/bigbluebutton-chatgpt#9]
Hi, I have a standalone installation of BBB version 2.6RC5 and followed the instructions to install chatGPT but it does not work. I got a npm version not updated message on installation when following the `sudo docker-compose up -d`

**Comment by arun-hel** [comment]
@amishbhavsar  #10  should fix this issue.

Pull the latest code and run `docker-compose up -d`

**Comment by amishbhavsar** [comment]
Excellent! It works now!!

**Comment by amishbhavsar** [comment]
Is there a way to rename "chatGPT" to another name?
So, instead of @chatGPT, may be we can call @anothername
And also change the icon 🤖 to another icon? Basically, I am checking if this can be branded.

**Comment by arun-hel** [comment]
@amishbhavsar You can change `@chatGPT` and icon in `app.js`

Since the issue regarding npm version is resolved, i will be closing this.

**Comment by arun-hel** [comment]
@amishbhavsar  #11  will allow you to change `@chatgpt` to `@anothername` 

1. Pull the latest code  `git pull`
2. We have added some env `CHAT_GPT_MODEL`, `CHAT_GPT_COMMAND`, `CHAT_GPT_ICON` so update your .env. Refer [sample-env](https://github.com/AsyncWeb/bigbluebutton-chatgpt/blob/main/sample-env)
3. Restart your docker container `docker-compose down && docker-compose up -d`

**Comment by amishbhavsar** [comment]
So, just to clarify, I need to make the change in **both** sample-env file and also the app.js file - correct?

**Comment by arun-hel** [comment]
@amishbhavsar no just pull the latest code and reinstall it.
